name: mno_shared
description: Contains the definitions of the custom types (model) used across the Readium-2 Dart projects.
version: 0.1.2
homepage: https://github.com/Mantano/mno_shared_dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ^3.1.2
  collection: ^1.15.0
  crypto: ^3.0.1
  dartx: ^0.7.1
  dfunc: ^0.7.2
  equatable: ^2.0.3
  fimber: ^0.6.1
  http: ^0.13.3
  image: ^3.0.4
  intl: ^0.17.0
  meta: ^1.7.0
  path: ^1.8.0
  universal_io: ^2.0.4
  xml: ^5.1.0
  mno_commons:
    path: "../mno_commons_dart"

dev_dependencies:
  image_compare: ^1.1.1
  lints: ^1.0.1
  test: ^1.17.12
